version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    target-branch: master
    schedule:
      interval: daily
    groups:
      osu-game:
        patterns:
          - "ppy.osu.Game*"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/"
    target-branch: osurx
    schedule:
      interval: daily
    groups:
      osu-game:
        patterns:
          - "ppy.osu.Game*"
          - "g0v0.osu.Game*"
    open-pull-requests-limit: 10
